echo ; > .\resource\common\main_form_view.js

echo ; >> .\resource\common\main_form_view.js
type .\resource\js\jquery-1.11.3.min.js          		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\ajaxPageProcess.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\ratchet.min.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\jquery.swiper-3.3.1.min.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\homepage.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\menu.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\flowCenter.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\common.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\jquery.cookie.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\tableList.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\jquery.lazyload.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\swiper.min.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\iscroll.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\dateField\mobiscroll\js\mobiscroll.custom-2.14.4.min.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\obpm.form.util.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\inputField\obpm.inputField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\buttonField\obpm.buttonField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\textareaField\obpm.textareaField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\checkboxField\obpm.checkboxField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\radioField\obpm.radioField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\selectField\obpm.selectField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\dateField\obpm.dateField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\upload\obpm.fileUpload.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\onlinetakephoto\obpm.onlineTakePhoto.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\map\obpm.baiduMap.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\departmentField\obpm.departmentField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\viewDialogField\obpm.viewDialogField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\treeDepartmentField\obpm.treeDepartmentField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\userField\obpm.userField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\userbox\jquery.userbox.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\includedView\obpm.plugin.includedView.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\includedView\obpm.includedView.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\wordField\obpm.wordField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\flowHistoryField\obpm.flowHistoryField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\flowReminderHistoryField\obpm.flowReminderHistoryField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\weixinGpsField\obpm.weixinGpsField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\surveyField\obpm.surveyField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\weixinImageUpload\obpm.weixinImagePinchzoom.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\weixinImageUpload\obpm.weixinImageUpload.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\weixinRecord\obpm.weixinRecord.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\qrcodeFiled\obpm.qrcodeField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\qrcodeFiled\lib\jquery.qrcode-0.12.0.min.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\upload\obpm.fileUpload.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\htmlEditor\obpm.htmlEditorField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\selectAboutField\obpm.selectAboutField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\selectAboutField\jquery.multiselect2side.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\suggest\obpm.suggestField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\suggest\typeahead.min.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\tabField\ddtabmenu.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\tabField\obpm.tabField.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\tabField\collapse\collapse.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\pending\obpm.pending.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\dialog\dialog.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\jquery-obpm-extend.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\artDialog\obpm-jquery-bridge.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\obpm.popup.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\document\obpm.ui.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\document\document.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\workflow\runtime\flowhistory.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\workflow\flowProcess.free.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\..\share\script\jSignature\jSignature.min.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\weixin\weixin.jsApi.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\view\common.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\view\view.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\view\obpm.listView.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\view\obpm.displayView.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.core.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.saveStartWorkflow.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.WorkflowProcess.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.save.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.saveBack.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.saveWithoutValidate.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.saveCloseWindow.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.saveNew.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.back.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.none.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.saveCopy.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.closeWindow.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.htmlPrint.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.htmlPrintWithHis.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.flexPrint.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.exportToPdf.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.fileDownload.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.signature.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.transpond.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.jumpTo.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.create.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.delete.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.clearAll.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.query.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.batchApprove.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.exportToExcel.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.printView.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.excelImport.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.batchSignature.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.archive.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\activity\obpm.activity.startWorkflow.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\component\confirm\obpm.confirm.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\util.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\list.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\template.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\backbone.route.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\phone.router.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\echarts.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\resource\js\report\oReport.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js
type .\..\share\script\jquery.watermark.js           		>> .\resource\common\main_form_view.js
echo ; >> .\resource\common\main_form_view.js


java -jar yuicompressor-2.4.8.jar .\resource\common\main_form_view.js -o .\resource\common\main_form_view.min.js



type .\resource\css\ratchet.min.css         > .\resource\common\main_form_view.css   
type .\resource\css\weui.min.css         	>> .\resource\common\main_form_view.css   
type .\resource\css\swiper.min.css        	>> .\resource\common\main_form_view.css   
type .\resource\css\font-awesome.min.css    >> .\resource\common\main_form_view.css   
type .\resource\css\global.css         		>> .\resource\common\main_form_view.css   
type .\resource\css\animate.css         	>> .\resource\common\main_form_view.css   
type .\resource\css\launch.css         		>> .\resource\common\main_form_view.css   
type .\resource\css\other.css         		>> .\resource\common\main_form_view.css 
type .\resource\css\documentModule.css      >> .\resource\common\main_form_view.css
type .\resource\component\selectAboutField\css\jquery.multiselect2side.css        		>> .\resource\common\main_form_view.css
type .\resource\component\dateField\mobiscroll\css\mobiscroll.custom-2.14.4.min.css        		>> .\resource\common\main_form_view.css
type .\resource\component\weixinImageUpload\obpm.weixinImageUpload.css        			>> .\resource\common\main_form_view.css
type .\resource\component\weixinRecord\obpm.weixinRecord.css        			>> .\resource\common\main_form_view.css
type .\resource\css\flowProcess.css        								>> .\resource\common\main_form_view.css
type .\resource\document\main-front.css        		>> .\resource\common\main_form_view.css
type .\resource\css\new.css        			>> .\resource\common\main_form_view.css
type .\resource\css\report.css        			>> .\resource\common\main_form_view.css
type .\resource\css\css.css         		>> .\resource\common\main_form_view.css  


java -jar yuicompressor-2.4.8.jar .\resource\common\main_form_view.css -o .\resource\common\main_form_view.min.css


@echo off
for %%i in (".\resource\common\main_form_view.min.js")do (
  set str=%%~ti%%~zi)
set "str=%str:/=%"
set "str=%str: =%"
set "str=%str::=%"


set script="<script type='text/javascript' src='<s:url value='/portal/phone/resource/common/main_form_view.min.js?v=%str%'/>'></script>"
set css="<link rel='stylesheet' href='<s:url value='/portal/phone/resource/common/main_form_view.min.css?v=%str%'/>'/>"

set /p=%script%<nul > ./resource/common/main_form_view_js.jsp
set /p=%css%<nul > ./resource/common/main_form_view_css.jsp
